#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint && npm run test || (
    echo 'ESLint failed. Please read the errors above.'
)

echo 'All checks passed.'

echo 'Commiting your changes.'